name: Test app
on:
  pull_request:
    # types: [opened, edited, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
      - name: Install playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run tests
        run: npm run e2e
      - name: Run test-ci
        run: npm run test-ci
  commitlint:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
  build:
    runs-on: ubuntu-latest
    needs: commitlint
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Predeploy app
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: pipe-cd/actions-gh-release@v2.3.4
        with:
          release_file: '**/RELEASE'
          token: ${{ secrets.GITHUB_TOKEN }}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        # with:
        #   tag_name: ${{ github.ref }}
        #   release_name: Release ${{ github.ref }}
        #   body: |
        #     Changes in this Release
        #     - First Change
        #     - Second Change
        #   draft: false
        #   prerelease: false
